/**
 * Created by li on 2018/3/1 13:05.
 */
export default{
    //article-item
    RECEIVE_ALL_POSTS : 'RECEIVE_ALL_POSTS',
    POST_FOCUS : 'POST_FOCUS',
    POST_EDIT : 'POST_EDIT',
    POST_TITLE_EDIT : 'POST_TITLE_EDIT',
    POST_SAVE : 'POST_SAVE',
    POST_TITLE_SAVE : 'POST_TITLE_SAVE',
    POST_DELETE : 'POST_DELETE',
    POST_PUBLISH : 'POST_PUBLISH',
    POST_CONTENT_UPDATE : 'POST_CONTENT_UPDATE',
    POST_TITLE_UPDATE : 'POST_TITLE_UPDATE',
    POST_EXCERPT_UPDATE : 'POST_EXCERPT_UPDATE',
    POST_LAST_EDIT_TIME : 'POST_LAST_EDIT_TIME',
    POST_TAG_UPDATE : 'POST_TAG_UPDATE',
    POST_CREATE : 'POST_CREATE',
    ARTICLE_DELETE : 'ARTICLE_DELETE',
    //token
    SET_TOKEN : 'SET_TOKEN',
    DEL_TOKEN : 'DEL_TOKEN',
}